version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSOWRD=postgres
      - POSTGRES_DB=book
    ports:
      - "5432:5432"
  book-service:
    image: books-api:1.00
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/book
    ports:
      - "8080:8080"
    depends_on:
      - postgres